### ISSUE TITLE
Citing goalie and animate

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/goalie#115]
Currently relevant for me. Could we add a CITATION file for goalie and animate?

**Comment by jwallwork23** [comment]
When do you need the citations by? I wonder it would be possible to archive the Animate and Goalie versions as part of a Firedrake Zenodo release. If not, we could make bespoke ones - I've done that in the past for Pyroteus.

**Comment by ddundo** [comment]
Thanks Joe, probably in the next 1-2 months latest, so not too urgent :)

**Comment by jwallwork23** [comment]
Okay great, I'll plan to figure out a process for this next week.

**Comment by jwallwork23** [comment]
@ddundo What do you think of this new page?
https://github.com/mesh-adaptation/mesh-adaptation-docs/wiki/Citing

Are the instructions sufficiently clear?

**Comment by jwallwork23** [comment]
Note that so far there's only an example for Movement.

**Comment by ddundo** [comment]
Thanks @jwallwork23, looks good to me! Although if I may nitpick, instead of "add some text" I might prefer "add a title and description" :)

I haven't tried it out yet but I can try it today if you'd like to close the issue - and then we can delete the release I make.

**Comment by jwallwork23** [comment]
Hm it turns out we probably should add a `CITATION.cff` file. (See https://github.com/mesh-adaptation/movement/issues/90.) Will do that now.
