### ISSUE TITLE
KeyError in indicate_errors for steady fields in combined steady-unsteady fields

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/goalie#119]
Since #114 and different solution dictionary structures for steady and unsteady fields, [L160 and L162 in `indicate_errors`](https://github.com/pyroteus/goalie/blob/4d141bed71c2a280504987f15799897136d09dc9/goalie/go_mesh_seq.py#L159-L162) raise a KeyError. It happens when we have a combination of steady and unsteady fields, so they raise a KeyError for the "steady" fields which do not have the `FWD_OLD` key in their solutions dictionary.

I guess I'm the only one with this problem at the moment so I fixed it locally and we can address it properly in the future alongside #55

**Comment by jwallwork23** [comment]
Thanks for reporting this @ddundo. I do intend to get back to finishing your multiple variables issue but there have been various other changes blocking progress along the way. Currently, I'm waiting for #113 to go through. (Feel free to pick it up for review if you like.)

**Comment by ddundo** [comment]
This is actually not relevant since lagged fields will be extracted (see #188), so I'll close
