### ISSUE TITLE
Consistent time_partition variable

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/goalie#142]
@jwallwork23, I saw in #116 that you renamed `P = mesh_seq.time_partition` to `tp = mesh_seq.time_partition`. Is this what you'd prefer going forward?

**Comment by jwallwork23** [comment]
Yeah single character variable names are bad practice in general. It's probably okay for fields in demo code (e.g., `u`, `p`) that have a clear mathematical usage, but we should avoid them as far as possible.

**Comment by jwallwork23** [comment]
`tp` also more clearly means time partition than `P`.

**Comment by ddundo** [comment]
Thanks! :)
