### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/goalie#145]
Goalie can be very memory intensive, particularly when we have many timesteps in a subinterval. Is there a way we can annotate only some solutions on the tape?

**Comment by ddundo** [comment]
Actually it's more complicated than I thought. Storing mesh data (and whatever else is connected to it) is much much more memory intensive than function data. So, if we have 100 timesteps, it is probably less memory intensive to have 1 subinterval and 100 solutions on tape than to have 2 subintervals with 50 solutions on tape.

**Comment by ddundo** [comment]
Idea: use `yield` in `MeshSeq.solver`

**Comment by jwallwork23** [comment]
As discussed in meeting, start by opening a PR for the `solve_forward` optimisations.
