### ISSUE TITLE
Burgers demo hangs locally

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/goalie#160]
For some reason the first Burgers demo has started hanging for me when I run it in Pytest. Is anyone else seeing this?

Command:
```
pytest -v test_adjoint/test_demos.py::test_demos[burgers]
```

**Comment by jwallwork23** [comment]
Similarly for `burgers_oo`

**Comment by jwallwork23** [comment]
Also `burgers-hessian`

**Comment by ddundo** [comment]
@jwallwork23 these all pass fine for me. And I see that you mentioned https://github.com/mesh-adaptation/animate/issues/92 in another issue, which also works for me as I commented there. Are you using the docker image with `FROM firedrakeproject/firedrake-vanilla:2024-02` or still `firedrake-vanilla:latest`?

**Comment by jwallwork23** [comment]
> @jwallwork23 these all pass fine for me. And I see that you mentioned [mesh-adaptation/animate#92](https://github.com/mesh-adaptation/animate/issues/92) in another issue, which also works for me as I commented there. Are you using the docker image with `FROM firedrakeproject/firedrake-vanilla:2024-02` or still `firedrake-vanilla:latest`?

Thanks for checking. I'm not using a Docker installation at the minute, I'm using a local build.

**Comment by ddundo** [comment]
Hmm okay. It seems like the same demos as you mentioned in https://github.com/mesh-adaptation/goalie/pull/128#issuecomment-1980869071
