### ISSUE TITLE
Passing boundary conditions to MeshSeq

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/goalie#167]
Since boundary conditions are only used in the solver, it seems unnecessary to define a `get_bcs` function and then passing it to the mesh sequence. Especially when prescribing bcs can be done with a single/few lines of code within the solver.

@jwallwork23 what do you think? I think that removing this would simplify the demos and declutter the goalie code.

**Comment by jwallwork23** [comment]
Sure, feel free to give it a go and see if anything breaks :)

**Comment by ddundo** [comment]
Thanks @jwallwork23, I opened a PR :)

This doesn't necessarily change too much since nowhere in the code was it required to actually define `get_bcs`. It's similar with `get_form` - we don't need to pass it to the mesh sequence object unless we are calling `indicate_errors()`. I'm not sure if it would make sense to require that `get_form` is always passed...
