### ISSUE TITLE
Delete demo on Solid body rotation with multiple prognostic variables

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/goalie#171]
I think that the `solid_body_rotation_split.py` demo is written in a non-goalie way, which became apparent when working on #169. For example, the way it's written would not allow us to extend it to a goal-oriented approach.

It's also a very very specific case where all PDEs are the same. So I'm not sure how useful it is in general, and may even be misleading/confusing. E.g. I think that adding the `field` kwarg to `get_form` may be quite confusing to new users.

I would either:
- rewrite it in a goalie way - i.e. without the shortcut for different fields
- or remove it completely, since we have `gray_scott_split.py` to demonstrate how to deal with multiple variables (which I think is the point of the `solid_body_rotation_split.py` demo

What do you think @jwallwork23?

**Comment by jwallwork23** [comment]
Sure, feel free to delete it.
