### ISSUE TITLE
Use `sed` instead of `GOALIE_REGRESSION_TEST`

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/goalie#175]
Rather than confusing the demo content with environment variables, we should apply specific modifications with `sed` when running the test suite.

**Comment by ddundo** [comment]
You mentioned on the meeting that you don't really like the use of `sed` here. How about this instead:

demo.py:
```
end_time = 2000.0
print("end time", end_time)
```

test_demo.py
```
def test_demo(capsys):
    with open('demo.py', 'r') as file:
        demo_content = file.read()

    modified_demo_content = demo_content.replace('end_time = 2000.0', 'end_time = 10.0')
    exec(modified_demo_content)

    # Capture the print output to check that it worked
    captured = capsys.readouterr()
    assert "end time 10.0" in captured.out
```

Essentially the same thing, but more flexible and avoids changing the original script (I guess we'd have to create a copy of the script before using `sed`).

I think another option might be to use pytest's `monkeypatch` fixture and change the `end_time` attribute of `TimePartition` (e.g. in the gray_scott.py demo). But I'm not sure how that would work and it's more complicated anyway
