### ISSUE TITLE
Passing adaptation parameters to `fixed_point_iteration`

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/goalie#203]
At the moment we are passing adaptation parameters (i.e. those in `goalie.options`) to `MeshSeq`, which are then used in `fixed_point_iteration` methods. Since we will introduce the on-the-fly approach (#88) which might have different parameters, I think it would make more sense to pass these adaptation parameters directly to `fixed_point_iteration`.

What do you think @jwallwork23? I'm happy to take this on

**Comment by jwallwork23** [comment]
Hm maybe, but some of them would surely be in common? e.g., the metric-related ones.

**Comment by ddundo** [comment]
Sorry, it's not clear to me why metric-related parameters would "surely" be the same? :) I'd have though that it's not unreasonable to set different ones since on-the-fly approach cannot utilise space-time normalisation.

Besides, do we even use these metric parameters anywhere? Aren't the default parameters set in Animate and we always modify them with `RiemannianMetric.set_parameters()`?

**Comment by jwallwork23** [comment]
Yeah that's a good point. You're right - in light of our discussion the other day it would probably be good to drop these metric parameters anyway and leave that to Animate.
