### ISSUE TITLE
Don't use `get_form`

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/goalie#223]
Note: I think it would make sense to get rid of `get_form` since it's only used in `indicate_errors` and just combine it with `get_solver`. This would avoid complications with communicating time-dependent fields between `get_solver` and `get_form` inside the user code. We'd still need a way to communicate the form to goalie, though - could simply yield it, introduce some new `MeshSeq` method for it...

_Originally posted by @ddundo in https://github.com/mesh-adaptation/goalie/issues/73#issuecomment-2416145455_
            
This would also simplify user code. What do you think @jwallwork23?

**Comment by jwallwork23** [comment]
Yeah I agree we can get rid of it.

**Comment by acse-ej321** [comment]
@ddundo - if you `yield {'<field>': F}` from the solver and pass it through the `_solve_adjoint` function to `indicate_errors`, you probably don't need a new method; just catch and release of the yielded variable.
