### ISSUE TITLE
Fix links to API docs in demos

### ISSUE THREAD

**Issue by acse-ej321** [mesh-adaptation/goalie#229]
As @ddundo recently pointed out, you need ~. in front of :class: references in order to properly link to the API docs. These are absent in quite a few of the documentation references in the demos.

**Comment by ddundo** [comment]
We already have an open issue for this https://github.com/mesh-adaptation/mesh-adaptation-docs/issues/5. I've been thinking of just sprinting through demos and fixing this but I'd like to get a reliable doc builder first - hopefully after https://github.com/mesh-adaptation/mesh-adaptation-docs/pull/52 merges :)
